package projectgui;

import projectoop.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Personal
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form RegistersCoba
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernameLabel_Login = new javax.swing.JLabel();
        passwordLabel_Login = new javax.swing.JLabel();
        loginButton_Login = new javax.swing.JButton();
        usernameTextFiield_Login = new javax.swing.JTextField();
        passwordTextField_Login = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        registerLabel_Login = new javax.swing.JLabel();
        registerButton_Login = new javax.swing.JButton();
        bg_Login = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 37, -1, 24));

        usernameLabel_Login.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        usernameLabel_Login.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel_Login.setText("Username         ");
        jPanel1.add(usernameLabel_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 174, -1, -1));

        passwordLabel_Login.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        passwordLabel_Login.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel_Login.setText("Password          ");
        jPanel1.add(passwordLabel_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 248, -1, -1));

        loginButton_Login.setBackground(new java.awt.Color(255, 255, 255));
        loginButton_Login.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        loginButton_Login.setText("Login");
        loginButton_Login.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        loginButton_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButton_LoginMouseClicked(evt);
            }
        });
        jPanel1.add(loginButton_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 185, 45));

        usernameTextFiield_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFiield_LoginActionPerformed(evt);
            }
        });
        jPanel1.add(usernameTextFiield_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 211, 425, 30));
        jPanel1.add(passwordTextField_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 285, 425, 30));

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PrimoWallet");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 68, -1, 34));

        registerLabel_Login.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        registerLabel_Login.setForeground(new java.awt.Color(255, 255, 255));
        registerLabel_Login.setText("Don't have any account yet ? Register now !");
        registerLabel_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        registerLabel_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerLabel_LoginMouseClicked(evt);
            }
        });
        jPanel1.add(registerLabel_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, 40));

        registerButton_Login.setBackground(new java.awt.Color(0,0,0,0));
        registerButton_Login.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        registerButton_Login.setBorderPainted(false);
        registerButton_Login.setContentAreaFilled(false);
        registerButton_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButton_LoginActionPerformed(evt);
            }
        });
        jPanel1.add(registerButton_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 310, 40));

        bg_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectoop/icon/Artboard 1 copy.png"))); // NOI18N
        jPanel1.add(bg_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Connection Con = null;
    PreparedStatement pst = null;
    ResultSet Rs = null;
    Statement St = null;
    
    private void usernameTextFiield_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFiield_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFiield_LoginActionPerformed

    private void registerButton_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButton_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerButton_LoginActionPerformed

    private void loginButton_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButton_LoginMouseClicked
        
        if(usernameTextFiield_Login.getText().isEmpty() || passwordTextField_Login.getText().isEmpty() )
        {
            JOptionPane.showMessageDialog(this, "Please Enter Your Username and Password");
        }else{
            String Query = "select * from accounttb where Username='"+usernameTextFiield_Login.getText()+"' and Password='"+passwordTextField_Login.getText()+"'";
            try{
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/primodb","root","");
                St = Con.createStatement();
                Rs = St.executeQuery(Query);
                if(Rs.next()){
                    new MainMenu(Rs.getString(1), Rs.getDouble(6), Rs.getString(4)).setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Wrong Account Number Or Password");
                }
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_loginButton_LoginMouseClicked

    private void registerLabel_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLabel_LoginMouseClicked
        new RegistersCoba().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerLabel_LoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton_Login;
    private javax.swing.JLabel passwordLabel_Login;
    private javax.swing.JPasswordField passwordTextField_Login;
    private javax.swing.JButton registerButton_Login;
    private javax.swing.JLabel registerLabel_Login;
    private javax.swing.JLabel usernameLabel_Login;
    private javax.swing.JTextField usernameTextFiield_Login;
    // End of variables declaration//GEN-END:variables
}
